---
# tasks file for nrpe-config1

# Nagios NRPE Server role

# Include variables at the start so they're in scope
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Install our needed packages for each specific OS
- include: "packages-{{ ansible_os_family }}.yml"

# Create our config
- name: Create nrpe.cfg from template
  template: >
    src="nrpe-ubuntu.cfg.j2"
    dest="{{ nagios_nrpe_server_dir }}/nrpe.cfg"
    owner=root group=root mode=0644
    when: ansible_distribution == 'Ubuntu'
  notify: restart nagios-nrpe-server

# Create our config
 - name: Create nrpe.cfg from template
   template: >
     src="nrpe-debian.cfg.j2"
     dest="{{ nagios_nrpe_server_dir }}/nrpe.cfg"
     owner=root group=root mode=0644
     when: ansible_distribution == 'Debian'
   notify: restart nagios-nrpe-server
                     

# Create nrpe_ansible.cfg
- name: Create nrpe_ansible.cfg from template
  template: >
    src="nrpe_ansible.cfg.j2"
    dest="{{ nagios_nrpe_server_dir }}/nrpe_ansible.cfg"
    owner=root group=root mode=0644
  notify: restart nagios-nrpe-server

# Sync our plugins
- name: Copying the custom plugins to nagios plugins directory 
  copy: >
    src="{{ item }}"
    dest="{{ nagios_nrpe_server_plugins_dir }}/"
    owner=root group=root mode=0755
  with_fileglob:
    - plugins/*

# Ensure NRPE server is running and will start at boot
- name: Ensure NRPE server is running
  service: name="{{ nagios_nrpe_server_service }}" state=started enabled=yes
